services: 
  postgres: 
    image: postgres:18.0-alpine3.22
    restart: always
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgressql/data

volumes: 
  postgres_data:

